# Generated by Django 5.1 on 2025-02-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_datetime', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
                ('video_url', models.URLField(unique=True)),
            ],
        ),
    ]
